version: '3'

services:
  db:
    image: neo4j:3.4
    volumes:
      - db_data:$HOME/neo4j/data
      - logs:$HOME/neo4j/logs
    environment:
      NEO4J_AUTH: "neo4j/password"
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:4567
    volumes:
      - .:/app
    ports:
      - "4567:4567"
    depends_on:
      - db
volumes:
  db_data:
  logs: