version: '2'

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nest
      MYSQL_DATABASE: dev
    ports:
      - "3306:3306"
    restart: always
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:4567
    volumes:
      - .:/app
    ports:
      - "4567:4567"
    depends_on:
      - db
  notebook:
    build: .
    command: python manage.py shell_plus --notebook
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data: