# Generated by Django 2.0.1 on 2018-01-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='uri',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
