# Generated by Django 2.0.1 on 2018-01-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180115_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='app.Folder'),
        ),
        migrations.AlterField(
            model_name='image',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.Folder'),
        ),
        migrations.AlterField(
            model_name='record',
            name='uri',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
