# Generated by Django 2.0.1 on 2018-01-20 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180115_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
